{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.ffs",
    "module": "apollo-kotlin-ffs",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.0.jar",
          "url": "apollo-kotlin-ffs-0.0.0.jar",
          "size": 4559,
          "sha512": "53bfb7a3fcb774af39252479a7ebe20c7ba5ed4936c117a6c9c9c5f249c6bef222f9fdddddedd1cae181879f169d28974f02688e6e8b8250c08c490ebdc51e2e",
          "sha256": "48e3ee73cddbd7c517321349021f7a2c887099425fc8cf999df65c4438f0fd04",
          "sha1": "b937699352cae8da9a42a63650d4622e7699d62e",
          "md5": "bd8837371af1e69a1f81d3f36d1133d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-compiler",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.0.jar",
          "url": "apollo-kotlin-ffs-0.0.0.jar",
          "size": 4559,
          "sha512": "53bfb7a3fcb774af39252479a7ebe20c7ba5ed4936c117a6c9c9c5f249c6bef222f9fdddddedd1cae181879f169d28974f02688e6e8b8250c08c490ebdc51e2e",
          "sha256": "48e3ee73cddbd7c517321349021f7a2c887099425fc8cf999df65c4438f0fd04",
          "sha1": "b937699352cae8da9a42a63650d4622e7699d62e",
          "md5": "bd8837371af1e69a1f81d3f36d1133d1"
        }
      ]
    }
  ]
}
