{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.ffs",
    "module": "apollo-kotlin-ffs",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.0-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.0-SNAPSHOT.jar",
          "size": 4559,
          "sha512": "1c3f82ffbd12a234ba910ed90b4bfaafbc1d1dabb228aa207f31941ca3988fa9573dbc08e4bbf830faf878321df9c0ecfb34cc58b1f2c2dd81437581b6eaa599",
          "sha256": "8cc431276df8352c2d8fe7e999ac894dcddb546054b2a1d86c96fc34f731b27d",
          "sha1": "338a29caed1d2a67ad82dd21c8d619624d1eacd4",
          "md5": "31ca7db22e720e3441e825203984a85e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-compiler",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.0-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.0-SNAPSHOT.jar",
          "size": 4559,
          "sha512": "1c3f82ffbd12a234ba910ed90b4bfaafbc1d1dabb228aa207f31941ca3988fa9573dbc08e4bbf830faf878321df9c0ecfb34cc58b1f2c2dd81437581b6eaa599",
          "sha256": "8cc431276df8352c2d8fe7e999ac894dcddb546054b2a1d86c96fc34f731b27d",
          "sha1": "338a29caed1d2a67ad82dd21c8d619624d1eacd4",
          "md5": "31ca7db22e720e3441e825203984a85e"
        }
      ]
    }
  ]
}
