[versions]
apollo = "4.3.0"

[libraries]
apollo-compiler = { module = "com.apollographql.apollo:apollo-compiler", version.ref = "apollo" }

[plugins]
kgp = { id = "org.jetbrains.kotlin.jvm", version = "2.2.0" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
librarian = { id = "com.gradleup.librarian", version = "0.0.9" }
