{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.ffs",
    "module": "apollo-kotlin-ffs",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "size": 4559,
          "sha512": "6b1a621a11810a6f215841df078a88169a40013acb4d59caa46422fb64e4c55c5c7a5c3a1f14cfefd1abb04159097d3649c39eab6fd739c2235b97538d352c9f",
          "sha256": "f8491bcc2b0fa61c44e31851ef69ec89298c8830cc5c590527b71ef5f84d5582",
          "sha1": "4d526b329d8cc596a820f162395675656ac38c51",
          "md5": "9b9ebe2cc841c08c0a7a3c07e2513152"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-compiler",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "size": 4559,
          "sha512": "6b1a621a11810a6f215841df078a88169a40013acb4d59caa46422fb64e4c55c5c7a5c3a1f14cfefd1abb04159097d3649c39eab6fd739c2235b97538d352c9f",
          "sha256": "f8491bcc2b0fa61c44e31851ef69ec89298c8830cc5c590527b71ef5f84d5582",
          "sha1": "4d526b329d8cc596a820f162395675656ac38c51",
          "md5": "9b9ebe2cc841c08c0a7a3c07e2513152"
        }
      ]
    }
  ]
}
