{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.ffs",
    "module": "apollo-kotlin-ffs",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "size": 4559,
          "sha512": "cd2bce6de8fdd1d6a1e63a985c1e3bd35a4dd4722b053f3e13542f475f7de004a39ec7ab6983d9b0092b3ec22e0b6be8c357dee831ce591c1b0258e15a71815c",
          "sha256": "8b8dec6e90d2193c98af30721da3f1cc20815f3ce1558ce4625765975e97968f",
          "sha1": "acd0e2cc57c36ca6c6170e3ee12cb027f615a658",
          "md5": "87c66cd683f665dc2ef4df4fea9ef7d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-compiler",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "size": 4559,
          "sha512": "cd2bce6de8fdd1d6a1e63a985c1e3bd35a4dd4722b053f3e13542f475f7de004a39ec7ab6983d9b0092b3ec22e0b6be8c357dee831ce591c1b0258e15a71815c",
          "sha256": "8b8dec6e90d2193c98af30721da3f1cc20815f3ce1558ce4625765975e97968f",
          "sha1": "acd0e2cc57c36ca6c6170e3ee12cb027f615a658",
          "md5": "87c66cd683f665dc2ef4df4fea9ef7d4"
        }
      ]
    }
  ]
}
