{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.ffs",
    "module": "apollo-kotlin-ffs",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "size": 4559,
          "sha512": "58d33f0f059e3744218f2d1c28ddf034ef6c5cd3baa489ac003ee72bcff3542fe7298dd26d6504bc5e309e6fcffd67773c672f76e53b8038a14bb2b8dfa832b9",
          "sha256": "91469c3f56518e098f4d5928b62c13a9f2051d40d8bd995a3e3ef27c8051aada",
          "sha1": "a8f802fbd203e0110a4ab6b264760192d209020d",
          "md5": "782dc60b5c52ff4975225c1e7373dc53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-compiler",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "size": 4559,
          "sha512": "58d33f0f059e3744218f2d1c28ddf034ef6c5cd3baa489ac003ee72bcff3542fe7298dd26d6504bc5e309e6fcffd67773c672f76e53b8038a14bb2b8dfa832b9",
          "sha256": "91469c3f56518e098f4d5928b62c13a9f2051d40d8bd995a3e3ef27c8051aada",
          "sha1": "a8f802fbd203e0110a4ab6b264760192d209020d",
          "md5": "782dc60b5c52ff4975225c1e7373dc53"
        }
      ]
    }
  ]
}
