{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.ffs",
    "module": "apollo-kotlin-ffs",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "size": 4559,
          "sha512": "d9626bc76f20617a993a4b240a610277834a0e6856a78705758f956607f9bfea95b420a5ddd325c39b69f305fcb6ed29ed0ad0f353a27119c8ed144023159df1",
          "sha256": "8f41e6b7d8f595a5e8c37fc1199a501f5f67e0ede81e8484ea31dd80523ae515",
          "sha1": "3402f8136a371c2bf0fd17a1ce38465e7b657260",
          "md5": "7e9455c568a45120607fc580add30fd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-compiler",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "size": 4559,
          "sha512": "d9626bc76f20617a993a4b240a610277834a0e6856a78705758f956607f9bfea95b420a5ddd325c39b69f305fcb6ed29ed0ad0f353a27119c8ed144023159df1",
          "sha256": "8f41e6b7d8f595a5e8c37fc1199a501f5f67e0ede81e8484ea31dd80523ae515",
          "sha1": "3402f8136a371c2bf0fd17a1ce38465e7b657260",
          "md5": "7e9455c568a45120607fc580add30fd2"
        }
      ]
    }
  ]
}
