{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.ffs",
    "module": "apollo-kotlin-ffs",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "size": 4520,
          "sha512": "a3a4d9b40bcf56366358915b88610370e313ffd647c2be268100901b7343614c5d1bef4f0d5ca6fb8cc8fc1bbda990ecd411a599126d9864b39adcc6edd61af3",
          "sha256": "f64e5ca6b3061cb6338fce0ab1d2cf48c215513b94bd280165f3d4c7807bae66",
          "sha1": "e177d61665a7c8d8fec1ee1dfac3fd8782f6fb9b",
          "md5": "fc84d98471f4eeeb4d8441648d232c0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-compiler",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "url": "apollo-kotlin-ffs-0.0.1-SNAPSHOT.jar",
          "size": 4520,
          "sha512": "a3a4d9b40bcf56366358915b88610370e313ffd647c2be268100901b7343614c5d1bef4f0d5ca6fb8cc8fc1bbda990ecd411a599126d9864b39adcc6edd61af3",
          "sha256": "f64e5ca6b3061cb6338fce0ab1d2cf48c215513b94bd280165f3d4c7807bae66",
          "sha1": "e177d61665a7c8d8fec1ee1dfac3fd8782f6fb9b",
          "md5": "fc84d98471f4eeeb4d8441648d232c0e"
        }
      ]
    }
  ]
}
